### PR TITLE
Update index.js to work with Webpack 2.1.0-beta.20

### PR DESCRIPTION
**Pull request by unyo**

### CODE REVIEW

**Comment by GabLeRoux** [comment]
Duplicates #23 ;)

**Comment by wolfadex** [comment]
You also need to change the loaders to `<loadername>-loader`. See [webpack v1-v2 migration guide](https://webpack.js.org/guides/migrating/).

**Comment by wolfadex** [comment]
@unyo  if you'd like to update this PR then I'll merge it. Or if #23 is updated first I'll merge that as they're duplicate commits.

**Comment by wolfadex** [comment]
Closing this commit as a duplicate of #23.

**Pull request closed without merging**
