### PR TITLE
Fix broken file link

### PR DESCRIPTION
**Pull request by jperasmus**

### CODE REVIEW

**Comment by waxlamp** [comment]
Will someone be merging / releasing this PR?

**Comment by wolfadex** [comment]
You also need to change the loaders to `<loadername>-loader`. See [webpack v1-v2 migration guide](https://webpack.js.org/guides/migrating/).

**Comment by wolfadex** [comment]
@jperasmus if you'd like to update this PR then I'll merge it. Or if #25 is updated first I'll merge that as they're duplicate commits.

**Comment by jperasmus** [comment]
Cool, I can make the update @wolfadex

**Comment by jperasmus** [comment]
@wolfadex Should be good to go now.

**Pull request merged**
